package es.codeurjc.orderservice.types;

public enum OrderEventEnum {
	ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_FAILED,
	ALLOCATE_DELIVERY_ORDER, ALLOCATION_DELIVERY_SUCCESS, ALLOCATION_DELIVERY_FAILED,
	RESERVE_CREDIT, CREDIT_APPROVED, CREDIT_REJECTED
   
}
